.Dd July 31, 2017
.Dt UPDATE-PORTS 8
.Os
.Sh NAME
.Nm "ravenadm update-ports"
.Nd Update Ravenports tree to latest version
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
command installs or upgrades to the latest version of Ravenports (conspiracy collection).
If the currently installed version of Ravenports matches the latest version, that
information will be displayed and nothing more will happen.  The download and
installation steps are handled automatically by ravenadm.
.Sh SEE ALSO
.Xr ravenadm 8 ,
.Xr ravenadm-build 8 ,
.Xr ravenadm-build-everything 8 ,
.Xr ravenadm-check-ports 8 ,
.Xr ravenadm-configure 8 ,
.Xr ravenadm-dev 8 ,
.Xr ravenadm-force 8 ,
.Xr ravenadm-generate-repository 8 ,
.Xr ravenadm-generate-website 8 ,
.Xr ravenadm-purge-distfiles 8 ,
.Xr ravenadm-locate 8 ,
.Xr ravenadm-set-options 8 ,
.Xr ravenadm-status 8 ,
.Xr ravenadm-status-everything 8 ,
.Xr ravenadm-subpackages 8 ,
.Xr ravenadm-test 8 ,
.Xr ravenadm-test-everything 8
